"""Shared hard limits for v2.2 competitor discovery and analysis."""

COMPETITOR_DISCOVERY_CANDIDATE_LIMIT = 6
COMPETITOR_DISCOVERY_SUPPLEMENTAL_LIMIT = 3
COMPETITOR_MIN_COUNT = 1
COMPETITOR_MAX_COUNT = 3

# Compatibility alias for code where the historical constant meant the maximum
# supported competitors rather than the required cardinality.
COMPETITOR_COUNT = COMPETITOR_MAX_COUNT

COMPETITOR_SITE_DISCOVERY_LIMIT = 50
COMPETITOR_SITE_DEEP_LIMIT = 10
COMPETITOR_REVIEW_PAGE_SIZE = 8
COMPETITOR_REVIEW_PAGE_LIMIT = 4
COMPETITOR_REVIEW_SAMPLE_LIMIT = 30
COMPETITOR_PROVIDER_ATTEMPT_LIMIT = 15
